version: '3.8'
services:
    postgres_db:
        image: postgres:13.5
        container_name: test_bitu
        restart: always
        environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=1234
          - POSTGRES_DB=test_bitu
        volumes:
          - postgres_db:/var/lib/postgresql/data
        ports:
          - '5432:5432'
volumes:
    postgres_db:
        driver: local
